name: Auto Tag Release

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to fetch all Git history for tagging

      - name: Get version from commit message (or generate)
        id: version
        run: |
          # Extract version from commit message (e.g., "Release: v1.0.0")
          VERSION=$(git log -1 --pretty=%B | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' || echo "")
          if [ -z "$VERSION" ]; then
            # Fallback: Generate a timestamp-based tag
            VERSION="v$(date +'%Y.%m.%d.%H%M%S')"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
